VERZIJA=CDX
MODUL=epdv_rpt

SRCDOSROOT=$(BASEDOS)\\fmk\\epdv\\rpt\\

PRGS=m_rpt.prg rpt_kif.prg rpt_kuf.prg rpt_pdv.prg r_lista.prg
#test.prg
CS=
ASMS=

include ../../fmk_lib/Makefile_clipper
